### ISSUE TITLE
AttributeError: 'list' object has no attribute 'join'

### ISSUE THREAD

**Issue by vikjam** [edemaine/slack-backup#1]
Thanks for sharing your scripts! I think I managed to get everything working, but I was just curious about this line. It seems like maybe a typo? I got this error:

```
AttributeError: 'list' object has no attribute 'join'
```

https://github.com/edemaine/slack-backup/blob/e87dfaea85224166ce1829fdce7ad918d94d9de0/slack_backup.py#L73

I think it should actually be `" & ".join(verbs)`. Thanks again!

**Comment by edemaine** [comment]
Thanks for pointing this out! I've pushed the fix you suggested.
