### ISSUE TITLE
How to read/view downloaded messages?

### ISSUE THREAD

**Issue by kingsloi** [edemaine/slack-backup#2]
Hi,

Thanks for this! I ran into a few issues, mainly with 404s and incomplete reads, so I added a few try/catches, but managed to download many years of Slack messages & files. 

I'm able to view the files, but do you have any idea how to read/view/digest the `<channel>/all.json` file?

I've tried to search for a Slack Messages viewer, but most of them need an official Slack export, not a .json file. 

Cheers

**Comment by edemaine** [comment]
Feel free to submit your additional `try`/`catch`es in a PR!

I've mainly used slack-to-discord to "visualize" the data in a Discord server. If you make the server private, only you will be able to see it (though of course you'd also be transmitting the data to another company).  I'm not aware of a suitable viewer, though that'd be an interesting project.

**Comment by kingsloi** [comment]
I did a few other things, like only grab the actual image (ignore any generated thumbnails) but I'll be honest, it's the first python code I've ever typed, so it may be a lil rough around the edges. I'll submit it as a PR though!

**Comment by kingsloi** [comment]
I  submitted a PR. 

I also [created an app](https://github.com/kingsloi/slack-backup-viewer) to generate a cheap node.js server to digest and display/view the backup. It's nothing special, but does the trick!
